Chameleon-company/Chameleon-Website

front_end_project/src/layouts/header/header.css, front_end_project/src/layouts/header/header.js
Designed a navigation bar (header) based on the images presented by the design team and added a drop-down menu to the resource.
=> header (Navigation bar)

front_end_project/src/pages/report/report.css, front_end_project/src/pages/report/report.js
contributions table updated on progress of report page
=> Janvig report

front_end_project/package-lock.json, front_end_project/src/layouts/header/header.js, front_end_project/src/pages/resources/resources.css, front_end_project/src/pages/resources/resources.js, package-lock.json
-Updated navigation bar to include What Is IoT section when hovering over resources tab.
-Emerging tech page has been updated to become What Is IoT page. This is to reflect identified updates to resources section discovered in sprint.
-Added new heading and subheading to What Is IoT? page
-Updated info rectangles to include two new sections, Internet of Things Technologies and IoT Statistics in Australia. These new sections will contain a brief introduction to these concepts, and link to more detailed information pages, which are yet to be added. Placeholder links are in place.
-Updated names of divs to be more reflective of their content.
=> Resources page and navigation bar updates

front_end_project/package-lock.json
fixed high security vulnerability 1/2
=> editing the code in front_end_project/package-lock.json

front_end_project/front_end_project/package-lock.json
editing code to fix high vulnerability
=> editing code in front_end_project/front_end_project/package-lock.json

front_end_project/src/App.js, front_end_project/src/layouts/header/header.js, front_end_project/src/pages/resources/iotStatistics.js, front_end_project/src/pages/resources/iotTechnologies.js, front_end_project/src/pages/resources/iotUpdates.js, front_end_project/src/pages/resources/resources.js
- Added new pages to resource section including what is IoT, IoT statistics in Australia and latest IoT updates. New pages currently contain placeholder lorem ipsum for written content to be added later.
- Updated placeholder resource links to link to their respective new pages.
- Updated navigation bar to include new resource sections.
- Imported new resource pages into App.js file and added paths to respective pages, allowing navigation to new resource pages from running website.
- Minor component name changes in resource section.
=> Add new pages to resource sections, other improvements

front_end_project/package-lock.json, front_end_project/src/pages/about/aboutUs.js
**Pull Request: Update About Us Page Content**
This pull request includes updates to the content for the About Us page, specifically:
1. **Company Overview**: We've revised and improved the company overview section to provide a clearer and more engaging description of our organization.
2. **FAQs**: We've added detailed answers to frequently asked questions (FAQs) to ensure visitors to the About Us page can find the information they need easily.
These updates enhance the About Us page and improve the overall user experience. Please review and merge at your earliest convenience.
Thank you!
=> About Us Page Content Upload

front_end_project/src/pages/homepage/Homepage.js, front_end_project/src/pages/homepage/Our_Project.css
i have created the hovering effect for the projects on the homepage. One more thing, all the elements were in "Class" not "ClassName". I don't know but I have now updated it too. and now the hover is also working. thankyou.
=> projects-hovering

front_end_project/src/pages/signup/sign up page updated with js file
=> Create sign up page updated with js file

front_end_project/package-lock.json, front_end_project/package.json, front_end_project/src/pages/Chatbot/Chatbot.js
Can't figure out how to get the UI working
=> Added the chatbot seperately from the UI

front_end_project/src/pages/login/login.js, front_end_project/src/pages/utils/firebase.js
1. Changed the apiKey, etc. in the front_end_project/src/pages/utils/firebase.js path to what I set.
2. Wrote the code that implements firebase under the login.js code I wrote and commented it out.
=> Staff login portal update

front_end_project/front_end_project/src/pages/utils/firebase.js, front_end_project/src/pages/Chatbot/Chatbot.js, front_end_project/src/pages/projects/projects.js
-Updated spelling errors on projects page
-Resolved chatbot file error, feature not enabled in current build as further refinements required
-Removed students API key from firebase file, to be replaced with Chameleon company one at later date
=> InnoFes revisions

front_end_project/public/index.html, front_end_project/src/pages/Chatbot/Chatbot.js, front_end_project/src/pages/about/aboutUs.js
Made changes to front_end_project/index.js (added CSP headers). And made some minor adjustments to accommodate follow CSP like changing YouTube links format (using embed instead of watch). Commented out one line in Chatbot.js (invalid import).
=> ADDED: CSP headers added to index.html

front_end_project/src/pages/login/login.js
Migrate all react-bootstrap to HTML and Tailwind CSS for Login Page. Also formatted the codes with Prettier.
=> Css migration login page

front_end_project/src/components/portfolio_card/porfolio_card.js, front_end_project/src/pages/projects/projects.js
Migrate all react-bootstrap to HTML and Tailwind CSS for Projects Page, except the Carousel component. That component will be done separately.
=> Css migration project page

front_end_project/src/pages/login/login.js
Reverts Chameleon-company/Chameleon-Website#115
=> Revert "react-toastify"

front_end_project/package-lock.json, front_end_project/package.json, front_end_project/src/App.js, front_end_project/src/components/notificationComp/NotificationComponent.js, front_end_project/src/pages/contact/contact.js
Currently applicable for Contact Page only
=> separate pop-up notification component created

front_end_project/src/App.js, front_end_project/src/layouts/footer/footer.js
The aim of this PR is fixing the bug from #121 
- a53cd19b052a4f41720f1755fd8ccd0d4d5beef9 Fixed the bug by using Flexbox solutions from [here](https://css-tricks.com/couple-takes-sticky-footer/#aa-there-is-flexbox)
This is the ideal solution as this scales when content gets added to the pages.
**Footer before** 
**Footer after**
=> Fix: Footer to the bottom of the page

front_end_project/src/pages/news/news.jsx
Fix the infinite scroll that cause large amount information make webpage overload.
=> Fix issue 139 Infinite scroll

front_end_project/src/layouts/footer/footer.js
Change background colour to white.
=> Fix Light / Dark Theme Issue 2

front_end_project/.dockerignore, front_end_project/dockerfile, front_end_project/nginx/nginx.conf
The aim of this PR is to set up config for building Docker app and serving on an Nginx server
- 87cb82c346b7e3629511d62e74643d6514ff8fa7 Configured Dockerfile and Dockerized React App
- 0c99383c002bc2e2fa84eaf18936eb7a17040bbe Configured Nginx Server and set to listen on port 80
Docker build successful
Container running successfully. Mapping port 3000:80
=> Docker and Ngnix config for React build prod

README.md
Corrected documentation on dependency installation.
The dependency installation instruction is incorrect. Fixed the documentation. 
P.S. This is also a test to initiate GitHub Action Runner
=> Fix - Update README.md

.github/workflows/build.yaml
Updated GCP auth workflow with new Auth@v0 as the previous version has been depreciated
=> BugFix - CI/CD Workflow build.yaml

back_end_project/controllers/newsController.js, back_end_project/routes/newsRoutes.js, back_end_project/server.js, back_end_project/services/newsService.js
This commit implements the News Management API using Firebase Firestore. Changes include:
- Added CRUD operations for news items.
- Created a service layer to handle database interactions.
- Developed controllers to process HTTP requests and responses.
- Set up Express routes for news management endpoints.
- Ensured all news items include necessary fields for data consistency.
- Wrote comprehensive API documentation detailing available endpoints, request formats, and example responses.
- Conducted thorough testing with Postman to ensure functionality and reliability of all API endpoints.
=> feat: Implement News Management API with Firebase

front_end_project/src/pages/login/login.css, front_end_project/src/pages/login/login.js, front_end_project/src/pages/signup/signup.css
Updated CSS for login and signup pages:
- Ensured proper display on the website
- Resolved conflicts with other page styles
=> Updated CSS for login and signup pages

front_end_project/src/components/card/card.js, front_end_project/src/pages/about/aboutUs.js, front_end_project/src/pages/calendar/calendar.js, front_end_project/src/pages/contact/contact.js, front_end_project/src/pages/email_newsletter_forms/remove.js, front_end_project/src/pages/email_newsletter_forms/subscribe.js, front_end_project/src/pages/email_newsletter_forms/unsubscribe.js, front_end_project/src/pages/login/login.js, front_end_project/src/pages/news/news.jsx, front_end_project/src/pages/report/report.js, front_end_project/src/pages/reset_password/reset.js, front_end_project/src/pages/resources/iotUpdates.jsx
instead of current 16 to prevent deprecation in future  and any vulnerabilities as well. The code base has been updated.
=> Updated: Entire code base to react 18

back_end_project/package-lock.json, front_end_project/src/App.js, front_end_project/src/pages/error404/404.js
- Made a customised error 404 page. 
- Any non-existent routes will get directed to this page.
=> New Page/Feature - Customized Error 404

front_end_project/src/App.js, front_end_project/src/pages/profile/password.js, front_end_project/src/pages/profile/posts.js, front_end_project/src/pages/profile/profile.js, front_end_project/src/pages/profile/user.js
Create Profile Screen
- Edit user data
- Change Password
- View posts
=> Umair profile component

front_end_project/src/components/about/About.jsx, front_end_project/src/components/about/FAQS.jsx, front_end_project/src/components/app/Screen.js, front_end_project/src/components/news/articleCard.jsx, front_end_project/src/components/news/filterBar.jsx, front_end_project/src/components/portfolio_card/porfolio_card.js, front_end_project/src/components/projects/ProjectCard.jsx, front_end_project/src/components/resources/iotResources.jsx, front_end_project/src/layouts/header/header.js, package.json
the code documentation has been updated for faster debugging and updation.
=> code documentation

front_end_project/package.json, front_end_project/public/index.html, front_end_project/src/constants/navigation.js, front_end_project/src/index.js, front_end_project/src/layouts/header/header.js
Merging header component including profile screen
=> Umair header profile

front_end_project/src/pages/resources/iotResources.jsx
=> Umair resources   fix title, css cards

front_end_project/package.json, front_end_project/src/pages/support/support.js
Fix CSS
Fix babel package
Reorder page structure
New page skeleton
=> Support Page Revamp

front_end_project/src/pages/resources/iotResources.jsx, front_end_project/src/pages/resources/iotStatistics.jsx, front_end_project/src/pages/resources/iotTechnologies.jsx, front_end_project/src/pages/resources/iotUpdates.jsx
Hi Team, I have done the following 
Resource Page: 
Fixed alignment of text, sizes and formatting.
Adding in some Chameleon Theme'd Colour to aspects of text to add consistency.
Each box of Technology, Statistics and Innovation is now expanded with a small blurb.
Technology Page:
Added consistency in Heading boldness and capitalisations.
Correct differentiating fonts
Amended overall alignement
Amended container spacing 
Amended text spacing
Statistics Page:
⁠Added consistency in Heading boldness and capitalisations.
Correct differentiating fonts
Amended overall alignement
Amended container spacing 
Amended text spacing
Innovation Page:
Added consistency in Heading boldness and capitalisations.
Correct differentiating fonts
Amended overall alignement
Amended container spacing 
Amended text …
=> Yuvi-fix-css-code-resources

front_end_project/src/pages/resources/iot.css, front_end_project/src/pages/resources/iotResources.jsx
=> Farit search feature

front_end_project/src/pages/login/login.css, front_end_project/src/pages/login/login.js
*Changes to UI components for better visual design
*Responsive design across differen sized screens
*Matching consistent styles with the overall website theme
*Clean design to attact user attention to important elements
*Removed redundant classes and selectors.
=> Enchanced and clean UI design

back_end_project/controllers/resourceController.js, back_end_project/routes/resourceRoutes.js, back_end_project/server.js, back_end_project/services/resourceService.js, front_end_project/package.json, front_end_project/src/pages/resources/iotStatistics.jsx
Successfully fetched iotStatistics page's content from the backend via GET request
=> Fetched from Backend part1

front_end_project/src/pages/error404/404.css
- Set html element background to grey
- Made html element to have a height of 100% for full viewport height
=> Updated CSS to have background colour fit scrollable pages
